# Generated by Django 6.0.2 on 2026-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Weight per unit in kg — used for delivery fee calculation', max_digits=6),
        ),
    ]
